name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test:
    strategy:
      matrix:
        os: [ "macos-13", "macos-12" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Get Homebrew cache directory
        id: brew-cache
        run: echo "dir=$(brew --cache)/downloads" >> $GITHUB_OUTPUT

      - name: Update Homebrew
        run: |
          brew update --preinstall

      - name: Configure Homebrew cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.brew-cache.outputs.dir }}
          key: brew-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: brew-
    
      - name: Install Karabiner-Elements
        run: |
          env HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask karabiner-elements

      - name: Test
        run: ./test.sh
